export const ROUTES = {
  home: "/",
  about: "/about",
  services: "/services",
  servicesPrinting: "/services/printing",
  servicesPackaging: "/services/packaging",
  servicesDesign: "/services/design",
  servicesFrames: "/services/frames",
  servicesCac: "/services/cac",
  shop: "/shop",
  shopCategory: (categorySlug: string) => `/shop/${categorySlug}`,
  shopProduct: (productId: string) => `/shop/product/${productId}`,
  orderCheckout: "/order/checkout",
  orderPayment: "/order/payment",
  orderConfirmation: "/order/confirmation",
  track: "/track",
  contact: "/contact",
  faq: "/faq",
  terms: "/terms",
  admin: {
    login: "/admin/login",
    dashboard: "/admin/dashboard",
    orders: "/admin/orders",
    orderDetail: (orderId: string) => `/admin/orders/${orderId}`,
    products: "/admin/products",
    productsNew: "/admin/products/new",
    productEdit: (productId: string) => `/admin/products/${productId}`,
    campaigns: "/admin/campaigns",
    campaignsNew: "/admin/campaigns/new",
    reviews: "/admin/reviews",
    settings: "/admin/settings",
    analytics: "/admin/analytics",
  },
  api: {
    ordersCreate: "/api/orders/create",
    orderDetail: (orderId: string) => `/api/orders/${orderId}`,
    orderStatus: (orderId: string) => `/api/orders/${orderId}/status`,
    tracking: (trackingId: string) => `/api/tracking/${trackingId}`,
    products: "/api/products",
    productDetail: (productId: string) => `/api/products/${productId}`,
    campaigns: "/api/campaigns",
    reviews: "/api/reviews",
    reviewApprove: (reviewId: string) => `/api/reviews/${reviewId}/approve`,
    upload: "/api/upload",
    analytics: "/api/analytics",
    pdf: (orderId: string) => `/api/pdf/${orderId}`,
  },
} as const;