/**
 * FIRESTORE COLLECTION CONSTANTS
 * CLO Media Printing Press
 *
 * Single source of truth for all Firestore collection names.
 *
 * Rules:
 *   - Always import collection names from this file
 *   - Never hardcode collection name strings elsewhere
 *   - Prevents typos and makes renaming safe and easy
 *   - Safe to import on both client and server
 */

// ─────────────────────────────────────────────
// COLLECTION NAME CONSTANTS
// ─────────────────────────────────────────────

export const COLLECTIONS = {
  /**
   * Products available in the shop.
   * Fields: id, name, categoryId, basePrice100, basePrice50,
   *         hasDesignAddon, variants, images, isActive, isFeatured, etc.
   */
  PRODUCTS: "products",

  /**
   * Product categories (Printing, Packaging, Design, Frames, etc.)
   * Fields: id, name, slug, description, icon, displayOrder, isActive
   */
  CATEGORIES: "categories",

  /**
   * Limited-time marketing campaigns with price overrides.
   * Fields: id, title, productId, overridePrice, bannerImage,
   *         startTime, endTime, isActive
   */
  CAMPAIGNS: "campaigns",

  /**
   * Customer orders — the core business data collection.
   * Fields: id, trackingId, customerName, customerPhone,
   *         item, grandTotal, paymentStatus, orderStatus, etc.
   */
  ORDERS: "orders",

  /**
   * Customer reviews submitted after delivery.
   * Fields: id, orderId, customerName, rating, reviewText, isApproved
   */
  REVIEWS: "reviews",

  /**
   * Site-wide settings — single document collection.
   * Use DOCUMENT_IDS.SITE_SETTINGS as the document ID.
   * Fields: defaultDeliveryDays, bankName, bankAccount,
   *         bankAccountName, whatsappNumber, designAddonPrice, etc.
   */
  SETTINGS: "settings",

  /**
   * Homepage CMS content — single document collection.
   * Use DOCUMENT_IDS.HOMEPAGE_CONTENT as the document ID.
   * Fields: heroHeadline, heroSubheadline, trustPoints, featuredProductIds
   */
  HOMEPAGE_CONTENT: "homepageContent",

  /**
   * Daily analytics snapshots generated by admin dashboard.
   * Fields: date, totalRevenue, totalOrders, pendingOrders, topProducts
   */
  ANALYTICS_SNAPSHOTS: "analyticsSnapshots",

  /**
   * Admin user records — fully restricted, Admin SDK only.
   * Fields: uid, email, createdAt
   */
  ADMINS: "admins",
} as const;

// ─────────────────────────────────────────────
// TYPE: COLLECTION NAME UNION
// ─────────────────────────────────────────────

/**
 * Union type of all valid collection name strings.
 * Use this when a function accepts any collection name.
 *
 * Example:
 *   function getCollection(name: CollectionName) { ... }
 */
export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];

// ─────────────────────────────────────────────
// SINGLETON DOCUMENT IDS
// ─────────────────────────────────────────────

/**
 * Document IDs for collections that contain only one document.
 *
 * Firestore doesn't have a native "singleton document" concept,
 * so we use consistent document IDs across the codebase.
 */
export const DOCUMENT_IDS = {
  /**
   * The single settings document.
   * Path: settings/siteSettings
   */
  SITE_SETTINGS: "siteSettings",

  /**
   * The single homepage content document.
   * Path: homepageContent/main
   */
  HOMEPAGE_CONTENT: "main",
} as const;

export type DocumentId = (typeof DOCUMENT_IDS)[keyof typeof DOCUMENT_IDS];

// ─────────────────────────────────────────────
// CLOUDINARY FOLDER PATHS
// ─────────────────────────────────────────────

/**
 * Cloudinary folder structure constants.
 * Kept here for co-location with storage-related constants.
 * Also imported in Cloudinary service when needed.
 */
export const CLOUDINARY_FOLDERS = {
  ROOT: "clomedia",
  PRODUCTS: "clomedia/products",
  CAMPAIGNS: "clomedia/campaigns",
  INVOICES: "clomedia/invoices",
  REVIEWS: "clomedia/reviews",

  /**
   * Returns the order-specific folder for a given order ID.
   * Usage: CLOUDINARY_FOLDERS.orderPayment("ORD-123")
   */
  orderPayment: (orderId: string) => `clomedia/orders/${orderId}/payment`,
  orderDesign: (orderId: string) => `clomedia/orders/${orderId}/design`,
} as const;